server:
  port: 7479
spring:
  application:
    name: LOGISTICS-SERVICE
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/test_shop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.62.128
    port: 6379
    password: 123456

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerCon1nectionSize: 201
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    schema:
#      - classpath:department.sql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.senorita.model
  config-location: classpath:mybatis.xml


#注册eureka客户端
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: LOGISTICS-7479
    prefer-ip-address: true
